import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import mediaRoutes from './media.routes.js';
import consultationRoutes from './consultation.routes.js';
import bookingRoutes from './booking.routes.js';
import serviceCategoryRoutes from './serviceCategory.routes.js';
import serviceRoutes from './service.routes.js';
import productCategoryRoutes from './productCategory.routes.js';
import productRoutes from './product.routes.js';
import usedLaptopRoutes from './usedLaptop.routes.js';
import promoCodeRoutes from './promoCode.routes.js';
import cartRoutes from './cart.routes.js';
import orderRoutes from './order.routes.js';
import adminOrderRoutes from './admin_order.routes.js';
import adminBookingRoutes from './admin_booking.routes.js';
import adminUserRoutes from './admin_user.routes.js';
import adminSellRequestRoutes from './admin_sell_request.routes.js';
import adminReviewRoutes from './admin_review.routes.js';
import adminConsultationRoutes from './admin_consultation.routes.js';
import adminPCBuilderRoutes from './admin_pc_builder.routes.js';
import adminSettingsRoutes from './admin_settings.routes.js';
import adminDashboardRoutes from './admin_dashboard.routes.js';
import pcBuilderRoutes from './pcBuilder.routes.js';
import reviewRoutes from './review.routes.js';
import onlineQueryRoutes from './onlineQuery.routes.js';
import sectionRoutes from './section.routes.js';
import blogRoutes from './blog.routes.js';
import adminBlogRoutes from './admin_blog.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/user', userRoutes);
router.use('/media', mediaRoutes);
router.use('/consultations', consultationRoutes);
router.use('/bookings', bookingRoutes);
router.use('/service-categories', serviceCategoryRoutes);
router.use('/services', serviceRoutes);
router.use('/product-categories', productCategoryRoutes);
router.use('/products', productRoutes);
router.use('/used-laptops-marketplace', usedLaptopRoutes);
router.use('/promo-codes', promoCodeRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/admin/orders', adminOrderRoutes);
router.use('/admin/bookings', adminBookingRoutes);
router.use('/admin/users', adminUserRoutes);
router.use('/admin/sell-requests', adminSellRequestRoutes);
router.use('/admin/reviews', adminReviewRoutes);
router.use('/admin/consultations', adminConsultationRoutes);
router.use('/admin/pc-builder', adminPCBuilderRoutes);
router.use('/admin/settings', adminSettingsRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/pc-builder', pcBuilderRoutes);
router.use('/reviews', reviewRoutes);
router.use('/online-queries', onlineQueryRoutes);
router.use('/sections', sectionRoutes);
router.use('/blog', blogRoutes);
router.use('/admin/blog', adminBlogRoutes);

export default router;

